name: Deploy Images to GHCR

on:
  push:
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest

        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

            # Build the image with branch name as tag
          - name: 'Build processor Image'
            run: |
              docker build . --tag ghcr.io/fastmri-prostate-reconstruction/data-processsor:{{github.ref}}
              docker push ghcr.io/fastmri-prostate-reconstruction/data-processor:{{github.ref}}
